on: [pull_request]

permissions:
  contents: read
  checks: write
  actions: write
  statuses: write

jobs:
  Fortify-Mobb-example:
    runs-on: ubuntu-latest
    name: Run scan with Fortify and get automated fixes with Mobb

    steps:
      - name: Checkout repo to get code
        uses: actions/checkout@v3

      - name: Setup Node on this machine
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18

      - name: Setup Java on this machine
        uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: "19"

      - name: Setup Maven on this machine
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.6

      - name: Download and configure packages
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip sed

      - name: Download Fortify ScanCentral Client
        uses: fortify/gha-setup-scancentral-client@v2

      - name: Download Fortify on Demand Universal CI Tool
        uses: fortify/gha-setup-fod-uploader@v1

      - name: Package Code + Dependencies
        run: scancentral package -bt mvn -o fortify_package.zip

      - name: Perform SAST Scan
        run: |
          UPLOAD_OUTPUT=$(java -jar $FOD_UPLOAD_JAR \
            -z fortify_package.zip \
            -ep SingleScanOnly \
            -portalurl https://ams.fortify.com/ \
            -apiurl https://api.ams.fortify.com/ \
            -userCredentials ${{ secrets.FORTIFY_USER }} ${{ secrets.FORTIFY_TOKEN }} \
            -tenantCode ${{ secrets.FORTIFY_TENANT }} \
            -releaseId ${{ secrets.FORTIFY_RELEASE_ID }} \
            -ep 2 -pp 0 -I 1 -apf \
            -pp Queue \
            -n 'Triggered by GitHub Actions (${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})')
          SCAN_ID=$(echo "$UPLOAD_OUTPUT" | sed -n 's/Scan \([0-9]*\).*$/\1/p')

#          FORTIFY_USER=${{ secrets.FORTIFY_USER }} \
 #           FORTIFY_TOKEN=${{ secrets.FORTIFY_TOKEN }} \
  #          FORTIFY_TENANT=${{ secrets.FORTIFY_TENANT }} \
   #         node .github/scripts/fortify-wait-fpr.js "$SCAN_ID"

        shell: bash -l {0}

      - name: Archive fpr
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: fpr
          path: scandata.fpr

      - name: Run Mobb on the findings and get fixes
        if: failure()
        uses: mobb-dev/action@v1
        with:
          report-file: "scandata.fpr"
          api-key: ${{ secrets.MOBB_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
