on: [pull_request]

permissions:
  contents: read
  checks: write
  actions: write
  statuses: write

jobs:
  Fortify-Mobb-example:
    runs-on: ubuntu-latest
    name: Run scan with Fortify and get automated fixes with Mobb

    steps:
      - name: Checkout repo to get code
        uses: actions/checkout@v3

      - name: Setup Node on this machine
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18

      - name: Setup Java on this machine
        uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: "19"

      - name: Setup Maven on this machine
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.6

      - name: Download and configure packages
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip sed

      - name: Download Fortify ScanCentral Client
        uses: fortify/gha-setup-scancentral-client@v2

      - name: Download Fortify on Demand Universal CI Tool
        uses: fortify/gha-setup-fod-uploader@v1

      - name: Package Code + Dependencies
        run: scancentral package -bt mvn -o fortify_package.zip

      - name: Perform SAST Scan
        run: java -jar $FOD_UPLOAD_JAR -z fortify_package.zip -aurl $FOD_API_URL -purl $FOD_URL -rid "$FOD_RELEASE_ID" -tc "$FOD_TENANT" -uc "$FOD_USER" "$FOD_PAT" $FOD_UPLOADER_OPTS -n "$FOD_UPLOADER_NOTES"
        env:
          FOD_URL: "https://ams.fortify.com/"
          FOD_API_URL: "https://api.ams.fortify.com/"
          FOD_TENANT: ${{ secrets.FORTIFY_TENANT }}
          FOD_USER: ${{ secrets.FORTIFY_USER }}
          FOD_PAT: ${{ secrets.FOD_PAT }}
          FOD_RELEASE_ID: ${{ secrets.FORTIFY_RELEASE_ID }}
          FOD_UPLOADER_OPTS: "-ep 2 -pp 0 -I 1 -apf"
          FOD_UPLOADER_NOTES: 'Triggered by GitHub Actions (${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})'

      - name: Archive fpr
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: fpr
          path: scandata.fpr

      - name: Run Mobb on the findings and get fixes
        if: failure()
        uses: mobb-dev/action@v1
        with:
          report-file: "scandata.fpr"
          api-key: ${{ secrets.MOBB_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
